### ISSUE TITLE
Slider Creator

### ISSUE THREAD

**Issue by haweiko** [navelpluisje/figma-knob-creator#1]
A great addition to the knob creator would be a slider creator that animates the frames for horizontal or vertical sliders.

![image](https://github.com/navelpluisje/figma-knob-creator/assets/138784987/ec21803a-42ef-45fd-95ea-98a1466ca130)

**Comment by navelpluisje** [comment]
@haweiko I have some great news for you. My Slider creator has just been approved and is available now:
* Documentation: https://navelpluisje.github.io/figma-slider-creator/howto
* Plugin: https://www.figma.com/community/plugin/1275561670400781749/Slider-Creator

Let me know what you think of it. Don't forget to rate my plugins.

**Comment by haweiko** [comment]
@navelpluisje bruh, If I'd only been patient... In the meantime I hired a guy on Fiverr to create a slider creator for me. Tbh yours seems to be pretty great though. My plugin is missing the cap-range feature but has a dedicated bipolar feature.

I see myself using your plugin too though. Will donate some bucks for that. Thanks for creating this plugin!

**Comment by navelpluisje** [comment]
@haweiko Thank you so much for your donation. Is the bipolar not what I created with the `progress-center` option? Using that will result in 
<img width="190" alt="image" src="https://github.com/navelpluisje/figma-knob-creator/assets/1625221/0c7fa409-59c7-4116-8053-2b5e39e3d06d">

**Comment by haweiko** [comment]
Oh true, that is a bipolar slider. I didn't see that. I only did a quick check of your plugin so I might missed it. Great you have this feature as well. Now it is clear, your plugin is better haha

**Comment by navelpluisje** [comment]
That's good to hear. Thanx again
