### ISSUE TITLE
Horizontal frames instead of vertical

### ISSUE THREAD

**Issue by AlexFaub** [navelpluisje/figma-knob-creator#2]
Hi,
Would it be possible to add a feature to have horizontal frames instead of vertical?
I'm making custom knobs design for max msp and for some reason the built in knobs engin uses horizontal fram format instead of vertical (which seems pretty insane ahah)

It would be really appreciated if you could manage to do it :)

**Comment by AlexFaub** [comment]
I found a workaround for now :)
If after generating the frame I remove the group <<rotate>> by searching for it, higlighting everyhting and batch ungrouping i am then able to rotate the whole frame group and then rotate the individual frames.
The rotate group was preventing this since it would make the knobs not centered, so rotating the individual frames would mess everything up.

**Comment by navelpluisje** [comment]
Hi @AlexFaub , 
I've just updated the plugin. Added a field to set the name for the step frames and added an option for stacking the steps horizontal. Hope this works as you expected. Please let me know.

**Comment by AlexFaub** [comment]
It works like a charm!!! Thank you so so very much :)

**Comment by navelpluisje** [comment]
Cool, that's great to hear.
